[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
log_cli = false
log_level = WARNING
filterwarnings =
    ignore:Bitwise inversion .~. on bool is deprecated:DeprecationWarning:pandas.*
    ignore:.*coroutine.*was never awaited:RuntimeWarning
